import type { HabitatBiomeConfig } from './types';

export const HABITAT_BIOMES: Record<string, HabitatBiomeConfig> = {
  'eo-002': {
    id: 'accretion',
    recordId: 'eo-002',
    title: 'THE ACCRETION BASIN',
    concept: 'ACCUMULATION / MEMORY / WEIGHT / RESIDUAL STRUCTURE',
    terrainProfile: 'basin',
    terrainAmplitude: 4.8,
    contourCount: 13,
    rootDensity: 1,
    biofilmDensity: 1,
    signalNodes: 8,
    signalColor: 0xffffff,
    errorColor: 0xd9d9d9,
    fogColor: 0xd9d9d9,
    fogDensity: 0.008,
    creatureScale: 8.2,
    creatureRange: 2.3,
    events: [
      { type: 'fragment-emergence', weight: 4, duration: [8, 14] },
      { type: 'root-seek', weight: 3, duration: [7, 12] },
      { type: 'terrain-compression', weight: 2, duration: [9, 15] },
    ],
  },
  'eo-003': {
    id: 'resonance',
    recordId: 'eo-003',
    title: 'THE RESONANCE BASIN',
    concept: 'RESONANCE / PROPAGATION / INTERFERENCE / LISTENING',
    terrainProfile: 'resonance',
    terrainAmplitude: 3.2,
    contourCount: 16,
    rootDensity: 0.56,
    biofilmDensity: 0.44,
    signalNodes: 10,
    signalColor: 0xffffff,
    errorColor: 0xd9d9d9,
    fogColor: 0xd9d9d9,
    fogDensity: 0.007,
    creatureScale: 7.4,
    creatureRange: 1.3,
    events: [
      { type: 'inward-resonance', weight: 4, duration: [9, 15] },
      { type: 'interference', weight: 3, duration: [8, 13] },
      { type: 'terrain-breath', weight: 2, duration: [10, 16] },
    ],
  },
  'eo-004': {
    id: 'phototropic',
    recordId: 'eo-004',
    title: 'THE PHOTOTROPIC FIELD',
    concept: 'PHOTOTAXIS / SIGNAL / ATTRACTOR / LIGHT AS ENVIRONMENTAL FORCE',
    terrainProfile: 'terrace',
    terrainAmplitude: 1.45,
    contourCount: 7,
    rootDensity: 0.38,
    biofilmDensity: 0.5,
    signalNodes: 14,
    signalColor: 0xffffff,
    errorColor: 0xd9d9d9,
    fogColor: 0xd9d9d9,
    fogDensity: 0.006,
    creatureScale: 7.1,
    creatureRange: 1.65,
    events: [
      { type: 'cluster-open', weight: 4, duration: [8, 14] },
      { type: 'light-wane', weight: 2, duration: [7, 12] },
      { type: 'fibre-orient', weight: 3, duration: [9, 15] },
    ],
  },
  'eo-005': {
    id: 'radial',
    recordId: 'eo-005',
    title: 'THE RADIAL NURSERY',
    concept: 'DISTRIBUTION / GERMINATION / NETWORK / RESOURCE TRANSFER',
    terrainProfile: 'radial',
    terrainAmplitude: 1.15,
    contourCount: 9,
    rootDensity: 0.62,
    biofilmDensity: 0.66,
    signalNodes: 16,
    signalColor: 0xffffff,
    errorColor: 0xd9d9d9,
    fogColor: 0xd9d9d9,
    fogDensity: 0.0065,
    creatureScale: 7.8,
    creatureRange: 1.1,
    events: [
      { type: 'node-transfer', weight: 5, duration: [7, 12] },
      { type: 'path-failure', weight: 2, duration: [5, 9] },
      { type: 'node-germination', weight: 3, duration: [10, 16] },
    ],
  },
};

export function getBiomeConfig(recordId: string) {
  return HABITAT_BIOMES[recordId] ?? HABITAT_BIOMES['eo-002'];
}
